#!/bin/bash

# restorephotos 项目部署指南
# 由于环境限制，以下是手动部署的步骤

echo "========== restorephotos 项目部署指南 =========="
echo ""
echo "步骤1: 将代码传输到服务器"
echo "使用SFTP工具（如WinSCP）连接到服务器:"
echo "- 主机: 49.232.38.171"
echo "- 用户名: root"
echo "- 密码: Raveland2025."
echo "- 将本地 'd:\gitidea\备份\restorephotos' 目录上传到 '/gitidea/restorephotos'"
echo ""
echo "步骤2: 连接到服务器并安装依赖"
echo "ssh root@49.232.38.171"
echo "(输入密码: Raveland2025.)"
echo ""
echo "cd /gitidea/restorephotos"
echo "npm install"
echo ""
echo "步骤3: 构建并启动项目"
echo "npm run build"
echo "npm run start"
echo ""
echo "步骤4: 后台运行（可选）"
echo "# 使用PM2进行进程管理"
echo "npm install -g pm2"
echo "pm2 start npm --name 'restorephotos' -- run start"
echo ""
echo "步骤5: 验证部署"
echo "在浏览器中访问: http://49.232.38.171:3000"
echo ""
echo "========== 部署指南结束 =========="